// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTZIkOP-Q7iiEpjsSh84QcHfShkEhAQs',
    appId: '1:243137247009:web:054d87b587750447a8f060',
    messagingSenderId: '243137247009',
    projectId: 'safenest-d7241',
    authDomain: 'safenest-d7241.firebaseapp.com',
    storageBucket: 'safenest-d7241.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKa7a64Zjf7jsuw1hucDx8jmJWVBdb3Y',
    appId: '1:243137247009:android:7a1bdbe370640efea8f060',
    messagingSenderId: '243137247009',
    projectId: 'safenest-d7241',
    storageBucket: 'safenest-d7241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_vyqHlf9kvjcDXs69ZxkOtV6ZC8j7qE',
    appId: '1:243137247009:ios:a1a6a35cde95b984a8f060',
    messagingSenderId: '243137247009',
    projectId: 'safenest-d7241',
    storageBucket: 'safenest-d7241.firebasestorage.app',
    iosBundleId: 'com.example.aalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_vyqHlf9kvjcDXs69ZxkOtV6ZC8j7qE',
    appId: '1:243137247009:ios:a1a6a35cde95b984a8f060',
    messagingSenderId: '243137247009',
    projectId: 'safenest-d7241',
    storageBucket: 'safenest-d7241.firebasestorage.app',
    iosBundleId: 'com.example.aalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHTZIkOP-Q7iiEpjsSh84QcHfShkEhAQs',
    appId: '1:243137247009:web:543d45d73eced816a8f060',
    messagingSenderId: '243137247009',
    projectId: 'safenest-d7241',
    authDomain: 'safenest-d7241.firebaseapp.com',
    storageBucket: 'safenest-d7241.firebasestorage.app',
  );
}
